-- MySQL Script generated by MySQL Workbench
-- 09/07/16 15:28:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema curso_laravel
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_aeropuerto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_aeropuerto` (
  `id_aeropuerto` INT NOT NULL AUTO_INCREMENT,
  `aeropuerto` VARCHAR(300) NULL,
  PRIMARY KEY (`id_aeropuerto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_aerolineas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_aerolineas` (
  `id_aerolinea` INT NOT NULL AUTO_INCREMENT,
  `aerolinea` VARCHAR(45) NULL,
  `tarifapernocta` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id_aerolinea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_pernocta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_pernocta` (
  `id_llegadas` INT NOT NULL AUTO_INCREMENT,
  `num_pasajeros` INT NULL,
  `ruta` VARCHAR(45) NULL,
  `hora_llegada` TIME NULL,
  `hora_salida` TIME NULL,
  `fecha_llegada` DATE NULL,
  `id_aeropuerto` INT NOT NULL,
  `id_aerolinea` INT NOT NULL,
  PRIMARY KEY (`id_llegadas`, `id_aeropuerto`, `id_aerolinea`),
  INDEX `fk_tb_llegada_tb_aeropuerto_idx` (`id_aeropuerto` ASC),
  INDEX `fk_tb_llegada_tb_aerolineas1_idx` (`id_aerolinea` ASC),
  CONSTRAINT `fk_tb_llegada_tb_aeropuerto`
    FOREIGN KEY (`id_aeropuerto`)
    REFERENCES `mydb`.`tb_aeropuerto` (`id_aeropuerto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_llegada_tb_aerolineas1`
    FOREIGN KEY (`id_aerolinea`)
    REFERENCES `mydb`.`tb_aerolineas` (`id_aerolinea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
